import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

{/* <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
<head>
  <meta charSet="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body className="antialiased">
  <main className="main-content">
    {children}
  </main>
</body>
</html> */}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
<html> 
<head>
  <meta charSet="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head> 
 <body className="antialiased">
  <main className="main-content">
    {children}
  </main>
</body>
 </html>
  );
}
