import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { parseHTML } from '@/utils/html-parser';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getRootLayout() {
  const res = await fetch('https://b2b-accelerator.myshopify.com/', {
    next: { revalidate: 3600 } // Revalidate every hour
  });
  const html = await res.text();
  return parseHTML(html);
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { head, body } = await getRootLayout();
  
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <div dangerouslySetInnerHTML={{ __html: head }} />
      </head>
      <body className="antialiased">
        <div dangerouslySetInnerHTML={{ __html: body }} />
        <main className="main-content">
          {children}
        </main>
      </body>
    </html>
  );
}
